<?php

declare(strict_types=1);

namespace Flowd\PhirewallPresetOwaspCrs\Tests\Unit\Import;

use Flowd\PhirewallPresetOwaspCrs\Import\Importer;
use Flowd\PhirewallPresetOwaspCrs\Import\RuleFileTransformer;
use Flowd\PhirewallPresetOwaspCrs\Manifest;
use org\bovigo\vfs\vfsStream;
use org\bovigo\vfs\vfsStreamDirectory;
use PHPUnit\Framework\TestCase;

final class ImporterTest extends TestCase
{
    private function setUpPackageRoot(): vfsStreamDirectory
    {
        return vfsStream::setup('package');
    }

    /**
     * @return array<string, string>
     */
    private function sourceFiles(): array
    {
        return [
            'rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf' => <<<'CRS'
            SecRule ARGS "@rx union.*select" "id:942100,phase:2,block,tag:'paranoia-level/1'"
            SecRule ARGS "@rx sleep\(" "id:942160,phase:2,block,tag:'paranoia-level/2'"
            CRS,
            'rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf' => <<<'CRS'
            SecRule REQUEST_FILENAME "@pmFromFile restricted-files.data" "id:930130,phase:1,block,tag:'paranoia-level/1'"
            CRS,
            'rules/REQUEST-905-COMMON-EXCEPTIONS.conf' => <<<'CRS'
            SecRule ARGS "@rx a" "id:905100,phase:1,pass"
            CRS,
            'rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf' => 'SecRule ARGS "@rx x" "id:900900,block"',
            'rules/RESPONSE-950-DATA-LEAKAGES.conf' => 'SecRule ARGS "@rx y" "id:950100,block"',
            'rules/restricted-files.data' => ".env\n.git\n",
        ];
    }

    public function testWritesPerParanoiaLevelFilesDataFilesAndManifest(): void
    {
        $root = $this->setUpPackageRoot();
        $destination = vfsStream::url('package/resources/rules');

        $importReport = (new Importer())->import($this->sourceFiles(), 'v4.0.0', $destination, '2026-06-12T00:00:00+00:00', 'LICENSE TEXT');

        $this->assertTrue($root->hasChild('resources/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.pl1.conf'));
        $this->assertTrue($root->hasChild('resources/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.pl2.conf'));
        $this->assertTrue($root->hasChild('resources/rules/REQUEST-930-APPLICATION-ATTACK-LFI.pl1.conf'));
        $this->assertTrue($root->hasChild('resources/rules/restricted-files.data'));
        $this->assertTrue($root->hasChild('resources/rules/manifest.json'));
        $this->assertTrue($root->hasChild('resources/rules/LICENSE'));

        $this->assertSame('v4.0.0', $importReport->crsVersion);
        $this->assertSame([1 => 2, 2 => 1, 3 => 0, 4 => 0], $importReport->ruleCountsByParanoiaLevel);
        $this->assertSame(3, $importReport->keptRuleCount());
        $this->assertSame(['restricted-files.data'], $importReport->dataFiles);
        $this->assertContains('REQUEST-905-COMMON-EXCEPTIONS.conf', $importReport->sourceFiles);
        $this->assertNotContains('REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf', $importReport->sourceFiles);
        $this->assertNotContains('RESPONSE-950-DATA-LEAKAGES.conf', $importReport->sourceFiles);
        $this->assertSame(1, $importReport->droppedRuleCounts[RuleFileTransformer::REASON_NON_BLOCKING]);
        $this->assertSame(1, $importReport->droppedRuleCount());
    }

    public function testGeneratedRuleFileContainsHeaderAndSingleLineRules(): void
    {
        $this->setUpPackageRoot();
        $destination = vfsStream::url('package/resources/rules');

        (new Importer())->import($this->sourceFiles(), 'v4.0.0', $destination, '2026-06-12T00:00:00+00:00');

        $content = (string)file_get_contents($destination . '/REQUEST-942-APPLICATION-ATTACK-SQLI.pl1.conf');
        $this->assertStringContainsString('# Generated by flowd/phirewall-preset-owasp-crs', $content);
        $this->assertStringContainsString('OWASP CRS v4.0.0', $content);
        $this->assertStringContainsString('Apache-2.0', $content);
        $this->assertStringContainsString('id:942100', $content);
        $this->assertStringNotContainsString('id:942160', $content);
    }

    public function testWritesNoticeWhenUpstreamShipsOne(): void
    {
        $root = $this->setUpPackageRoot();
        $destination = vfsStream::url('package/resources/rules');

        (new Importer())->import($this->sourceFiles(), 'v4.0.0', $destination, '2026-06-12T00:00:00+00:00', 'LICENSE TEXT', 'NOTICE TEXT');

        $this->assertTrue($root->hasChild('resources/rules/NOTICE'));
        $this->assertSame('NOTICE TEXT', file_get_contents($destination . '/NOTICE'));
    }

    public function testNoNoticeFileWhenUpstreamHasNone(): void
    {
        $root = $this->setUpPackageRoot();
        $destination = vfsStream::url('package/resources/rules');

        (new Importer())->import($this->sourceFiles(), 'v4.0.0', $destination, '2026-06-12T00:00:00+00:00', 'LICENSE TEXT');

        $this->assertFalse($root->hasChild('resources/rules/NOTICE'));
    }

    public function testManifestRoundTripsThroughManifestReader(): void
    {
        $this->setUpPackageRoot();
        $destination = vfsStream::url('package/resources/rules');

        (new Importer())->import($this->sourceFiles(), 'v4.0.0', $destination, '2026-06-12T00:00:00+00:00');

        $manifest = Manifest::read($destination);
        $this->assertSame('v4.0.0', $manifest->crsVersion);
        $this->assertSame('2026-06-12T00:00:00+00:00', $manifest->importedAt);
        $this->assertSame([1 => 2, 2 => 1, 3 => 0, 4 => 0], $manifest->ruleCountsByParanoiaLevel);
        $this->assertSame(['restricted-files.data'], $manifest->dataFiles);
    }

    public function testRemovesFilesFromAPreviousImport(): void
    {
        $root = vfsStream::setup('package', null, [
            'resources' => [
                'rules' => [
                    'REQUEST-999-GONE.pl1.conf' => 'stale',
                    'gone.data' => 'stale',
                    'keep.txt' => 'untouched',
                ],
            ],
        ]);

        $destination = vfsStream::url('package/resources/rules');
        (new Importer())->import($this->sourceFiles(), 'v4.0.0', $destination, '2026-06-12T00:00:00+00:00');

        $this->assertFalse($root->hasChild('resources/rules/REQUEST-999-GONE.pl1.conf'));
        $this->assertFalse($root->hasChild('resources/rules/gone.data'));
        $this->assertTrue($root->hasChild('resources/rules/keep.txt'));
    }

    public function testFailsWhenAReferencedDataFileIsMissing(): void
    {
        $this->setUpPackageRoot();
        $sourceFiles = ['rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf' => 'SecRule REQUEST_FILENAME "@pmFromFile missing.data" "id:930130,block"'];

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('missing.data');

        (new Importer())->import($sourceFiles, 'v4.0.0', vfsStream::url('package/resources/rules'), '2026-06-12T00:00:00+00:00');
    }

    public function testFailsWhenNoRuleFilesAreFound(): void
    {
        $this->setUpPackageRoot();

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('No REQUEST-*.conf rule files');

        (new Importer())->import(['rules/README.md' => 'x'], 'v4.0.0', vfsStream::url('package/resources/rules'), '2026-06-12T00:00:00+00:00');
    }
}
